name: Build and Release AppImage

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install AppImage tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          
      - name: Prepare AppDir
        run: |
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/share/applications
          mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
          mkdir -p AppDir/usr/share/icons/hicolor/scalable/apps
          cp bersih AppDir/usr/bin/
          cp AppDir/bersih.svg AppDir/usr/share/icons/hicolor/scalable/apps/
          cp AppDir/bersih.png AppDir/usr/share/icons/hicolor/256x256/apps/
          chmod +x AppDir/usr/bin/bersih
          
      - name: Create AppImage
        run: |
          cp AppDir/bersih.desktop AppDir/usr/share/applications/
          chmod +x AppDir/AppRun
          chmod +x AppDir/usr/bin/bersih
          # Test AppRun script
          bash -n AppDir/AppRun
          # Build AppImage dengan flag debug
          ARCH=x86_64 ./appimagetool-x86_64.AppImage -v AppDir Bersih-x86_64.AppImage
          # Test AppImage
          chmod +x Bersih-x86_64.AppImage
          ./Bersih-x86_64.AppImage --version || true
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: Bersih-x86_64.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
